# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{beanstalkapp}
  s.version = "1.6.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ilya Sabanin"]
  s.date = %q{2011-11-30}
  s.email = %q{ilya.sabanin@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = Dir["{lib,test,doc}/**/*", "CHANGES.rdoc", "MIT-LICENSE", "Rakefile", "README.rdoc", "VERSION"]
  s.homepage = %q{http://api.beanstalkapp.com}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Official wrapper for Beanstalk API.}

  s.add_dependency(%q<activeresource>, ">= 2.3.5")
end

